app/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh|vi/ do
  
    resources :comments
    resources :posts
    devise_for :people, :controllers => { :invitations => 'people/invitations' }
    resources :companies, type: 'Company'  do
      member do
        post 'follow'
      end
    end

  
    get '/embed/:id' => 'supergroups#show', type: 'Union', embed: true
    get '/embed/:union_id/new' => 'recs#new', embed: true
    get '/embed/:union_id/review/:id' => 'recs#review', embed: true
  
    resources :unions, controller: :supergroups, type: 'Union' do
      member do
        post 'follow'
        get 'all'
      end
      resources :recs do
        member do
          post 'follow'
          get 'review'
          patch 'video_upload'
          get 'toggle' # get so it can be done from email link
        end
      end
    end
  
    resources :people
  
    resources :recs do
      member do
        post 'follow'
        get 'review'
        patch 'video_upload'
        get 'toggle' # get so it can be done from email link
      end
    end
  
    resources :submission, controller: :recs, type: 'Rec'
    
    get '/en' => "recs#index", locale: 'en'
    get '/zh' => "recs#index", locale: 'zh'
    get '/vi' => "recs#index", locale: 'vi'
    
    get '/:id' => 'supergroups#show', type: 'Union'
    get '/:union_id/new' => 'recs#new'
  
    root "recs#index"
  end 

end

app/app/views/layouts/_footer.html.erb
<% unless ENV['GA_TRACKING_ID'].blank? %>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', '<%=ENV['GA_TRACKING_ID']%>', 'auto');
	  ga('send', 'pageview');

	</script>
<% end %>

app/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="navbar-brand" href="/">
        <%= link_to union_logo, union_path(@union) %>
        <%= link_to ENV['APP_TITLE'], union_path(@union) %>
      </div>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if person_signed_in? -%>
          <li>
            <%= link_to "Unions", unions_path %>
          </li>
          <!--<li>
            <%= link_to "Companies", companies_path %>
          </li>-->
          <li>
            <%= link_to "People", people_path %>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" aria-expanded="false" area-haspopup="true" role="button" data-toggle="dropdown" href="#">
              <%= profile_thumb(current_person) %>
              <%= current_person.display_name %>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "my profile", edit_person_path(id: current_person.id) %>
              </li>
              <li>
                <%= link_to "invite an administrator", new_person_invitation_path %>
              </li>
              <li>
                <%= link_to "sign out", destroy_person_session_path, :method => 'delete' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "sign in", new_person_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<% if @union %>
		<!-- For facebook -->
		<meta property="og:title" content="<%=@union.call_to_action%>" />
		<meta property="og:type" content="article" />
		<meta property="og:image" content="<%=@union.facebook_image.url || @union.union_rep.url%>" />
		<meta property="og:image" content="<%=@union.banner.url %>" />
		<meta property="og:url" content="<%="#{request.protocol}#{request.host}/#{locale}/#{@union.short_name}/new"%>" />
		<meta property="og:description" content="<%=@union.explanation%>" />
	<% end %>

	<title><%=ENV['APP_TITLE']%></title>

	<!-- Google fonts -->
	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/navbar" %>
	<div class="container-fluid content-area">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title><%=ENV['APP_TITLE']%></title>

	<!-- Google fonts -->
	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid content-area">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>