app/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|zh|vi/ do
  
    resources :comments
    resources :posts
    devise_for :people, :controllers => { :invitations => 'people/invitations' }
    resources :companies, type: 'Company'  do
      member do
        post 'follow'
      end
    end

  
    get '/embed/:id' => 'supergroups#show', type: 'Union', embed: true
    get '/embed/:union_id/new' => 'recs#new', embed: true
    get '/embed/:union_id/review/:id' => 'recs#review', embed: true
  
    resources :unions, controller: :supergroups, type: 'Union' do
      member do
        post 'follow'
        get 'all'
      end
      resources :recs do
        member do
          post 'follow'
          get 'review'
          patch 'video_upload'
          get 'toggle' # get so it can be done from email link
        end
      end
    end
  
    resources :people
  
    resources :recs do
      member do
        post 'follow'
        get 'review'
        patch 'video_upload'
        get 'toggle' # get so it can be done from email link
      end
    end
  
    resources :submission, controller: :recs, type: 'Rec'
    
    get '/en' => "recs#index", locale: 'en'
    get '/zh' => "recs#index", locale: 'zh'
    get '/vi' => "recs#index", locale: 'vi'
    
    get '/:id' => 'supergroups#show', type: 'Union'
    get '/:union_id/new' => 'recs#new'
  
    root "recs#index"
  end 

end

app/app/models/rec.rb
class Rec < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
	
	belongs_to :company
	belongs_to :union
	belongs_to :person
	has_many :posts, :as => :parent
	accepts_nested_attributes_for :person

	#validates :union,  presence: true

	after_initialize :set_switch_defaults

	serialize :nature_of_operation, Array

	acts_as_followable

	before_validation :set_token, on: [:create]
	before_validation :hide_unaccepted, on: [:create, :update]

	def post_title
		"Post questions and supplementary information here"
	end

	def formatted_summary
		summary.split("\r\n").collect { |i| "<p>#{h i}</p>" }.join.html_safe
	end

	def self.questions 
		{
			pay_and_conditions: [
				:paid_fairly,
				:compliant_employment,
				:could_speak_up
			],
			health_and_safety: [
				:safe_work, 
				:safe_work_explained,
				:discuss_safety
			#	:hsr_explained
			],
			personal_impact: [
				:predictable_hours,
				:primary_carer,
				:entitlements
			#	:community_life
			], 
			financial_security: [
				:financially_stable,
				:accommodation_secure,
				:feeling_secure
			]
			#feeling_trapped: [
			#	:options
			#]

			#:formally_employed
			#:family_life
			#:secure_stay,
			#:family_life,
			#:prefer_flexibility
		}
	end

	def display_name
		result = ""
		if self.is_anonymous
			result = "Anonymous"
		else 
			result = self.person.display_name
		end
		result += ", #{self.location}" unless self.location.blank?
		result
	end

	def self.token
		# generate a vaguely readable/memorable token of alternating vowel and consonants
		v = %w[a e i o u]
		c = ('a'..'z').to_a
		c = c - v - ['x', 'q'] # I don't like the ones with x and q
		s = ""

		# 7 alternate vowels and consonants gives me 16M, the root of which is 4000, which is the number of submission before I've got even odds of colliding
		(1..7).each do |i|
			s << c[SecureRandom.random_number(c.count)] if i % 2 == 1
			s << v[SecureRandom.random_number(v.count)] if i % 2 == 0 
		end
		s = Rec.token if Rec.find_by_token(s) # recursively find another token, if this one is used
		s
	end

	def set_token
		self.token ||= Rec.token
	end

	def hide_unaccepted
		self.enabled = false if self.accept_terms == false
		true
	end

	def set_switch_defaults
		# this is a stop gap because I forgot to set the defaults initially
		Rec.questions.each do |k,v|
			v.each do |q|
				write_attribute q, true if self[q].nil?
			end
		end
	end
end

app/app/controllers/recs_controller.rb
class RecsController < ApplicationController
  before_action :authenticate_person!, except: [:index, :new, :create, :review, :video_upload]
  before_action :set_rec, only: [:show, :edit, :update, :destroy, :follow, :toggle]
  before_action :set_rec_from_token, only: [:review, :video_upload]

  include RecsHelper

  # GET /recs
  # GET /recs.json
  def index
    not_found if params[:format] == 'xls' && !owner?
    @recs = Rec.all.eager_load(:person).eager_load(:union)
    @recs = @recs.where(enabled: true) unless current_person
    @recs = @recs.order(created_at: :desc)
    @supergroup = @union # TODO is there a better way?

    respond_to do |format|
      format.html
      format.xls { render 'shared/export.xls' }
    end
  end

  # GET /recs/1
  # GET /recs/1.json
  def show
    @post = Post.new(parent: @rec)
  end

  # GET /recs/new
  def new
    @rec = Rec.new
    @rec.person = Person.new
    @rec.person.union = @union
    @rec.union = @union
    return render 'embed_new', layout: 'embed' if params[:embed]
  end

  # GET /recs/1/edit
  def edit
  end

  # After posting a submission
  def review
      return render 'embed_review', layout: 'embed' if params[:embed]
  end

  def video_upload
    respond_to do |format|
      if @rec.update(rec_params)
        format.json { render json: { url: @rec.attachment.url, content_type: @rec.attachment.content_type} }
      else
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /recs
  # POST /recs.json
  def create
    @rec = Rec.new(rec_params)
    
    # TODO fix this horrible mess
    respond_to do |format|
      if @rec.save
        notify
        thank
        
        # let unauthenticated users review with a temporary url
        success_url = current_person ? rec_url(@rec.id)  : secured_review_rec_url
        success_url = secured_embed_review_rec_url if params[:embed] == "true"

        format.html { redirect_to success_url, notice: 'The submission was successfully created.' }
        format.json { render :show, status: :created, location: @rec }
      else
        if params[:embed] == "true"
          result = render 'embed_new', layout: 'embed' 
        else
          result = render :new
        end if 
        format.html { result }
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recs/1
  # PATCH/PUT /recs/1.json
  def update
    respond_to do |format|
      if @rec.update(rec_params)
        format.html { redirect_to @rec, notice: 'The submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @rec }
      else
        format.html { render :edit }
        format.json { render json: @rec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recs/1
  # DELETE /recs/1.json
  def destroy
    @rec.destroy
    respond_to do |format|
      format.html { redirect_to recs_url, notice: 'The submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    current_person.toggle_follow!(@rec)
    redirect_to @rec
  end

  def toggle
    @rec.update(enabled: !@rec.enabled)
    redirect_to @rec
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rec
      @rec = Rec.find(params[:id])
    end

    def notify
      @rec.union.followers(Person).each do |p|
        if p.invitation_accepted_at
          can_edit = can_edit_union(@rec.union)
          PersonMailer.rec_notice(p, @rec, request, can_edit).deliver_now
        end 
      end
    end

    def thank
      PersonMailer.thanks(@rec.person, @rec, request).deliver_now
    end

    # allow a user to review their submission after posting, without letting them guess at other URLs and review things they should
    def secured_review_rec_url
      review_rec_url(@rec.token)
    end
  
    # allow a user to review their submission after posting, without letting them guess at other URLs and review things they should
    def secured_embed_review_rec_url
      "/embed/#{@union.id}/review/#{@rec.token}"
    end

    def set_rec_from_token
      @rec = Rec.find_by_token(params[:id])
      @rec = Rec.find(params[:id]) if @rec.nil? && current_person # only allow id if logged in (for video_upload from show)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rec_params
      #if params[:rec] && params[:rec][:person_attributes] && params[:rec][:person_attributes][:union_id].nil?
        # hack to save emma's first submision and workaround union_id bug
      #  params[:rec][:person_attributes][:union_id] = params[:rec][:union_id]
      #end
      result = params.require(:rec).permit(
        [
          :nature_of_employment,
          :when,
          :youtube, 
          :paid_fairly,
          :compliant_employment,
          :could_speak_up,
          :professional_development,
          :pay_and_conditions_comment,
          :safe_work,
          :safe_work_explained, 
          :discuss_safety,
          :hsr_explained,
          :induction, 
          :health_and_safety_comment,
          :predictable_hours,
          :primary_carer,
          :entitlements,
          :community_life,
          :personal_impact_comment,
          :financially_stable,
          :accommodation_secure,
          :feeling_secure, 
          :financial_security_comment,
          :options,
          :feeling_trapped_comment,
          :is_union,
          :host_employer,
          :company,
          :company_name,
          :location,
          :industry,
          :supermarket_supply,
          :solution,
          :summary,
          :is_anonymous,
          :union_id,
          :attachment,
          :accept_terms, 
          person_attributes: [
            :first_name, 
            :last_name, 
            :gender, 
            :email, 
            :mobile,
            :attachment, 
            :title, 
            :union_id,
            :volunteer,
            :id
          ]
        ]
      )
      result
    end
end

app/app/helpers/recs_helper.rb
module RecsHelper

	def nature_of_employment_options
		options_for_select(
				([
					t('noe_agency'),
					t('noe_contractor'),
					t("noe_affected")
					#t("noe_informal"), 
					#t('noe_agency'),
					#t('noe_casual'),
					#t('noe_rolling')
					]).uniq, 
				@rec.nature_of_employment
			)
	end

	def when_options
		options_for_select(
				([
					t("when_current"), 
					t("when_lt3"),
					t("when_lt12"),
					t("when_mt12")
					]).uniq, 
				@rec.when
			)
	end

	def union_options
		result = []
		Union.all.order(:short_name).each do |u|
			result << ["#{u.short_name}: #{u.name}", u.id]
		end
		result
	end

	def default_switch_options
		{ :size => 'small', 'on-text'=>t("switch_yes"), 'off-text'=>t("switch_no"), 'on-color'=>'success', 'off-color' => 'danger'}
	end

	def neutral_switch_options
		{ :size => 'small', 'on-text'=>t("switch_yes"), 'off-text'=>t("switch_no"), 'on-color'=>'success'}
	end

	def comment(q)
		"#{q.to_s}_comment"
	end

	def cell_style(bool)
		"style=\"color:#{ bool ? 'green' : 'red'};\"".html_safe
	end
end

app/app/views/recs/_detailed_rec.html.erb
<h3 class="rec-heading no-left-margin" style="color: red !important;">
	<a class="" href="<%= can_edit_union(rec.union) || can_edit_union(rec.person.union) ? edit_union_rec_url(rec.union, rec) : union_rec_url(rec.union, rec) %>">
		<% unless rec.is_anonymous %> 
			<%=rec.person.first_name %>
			<%=rec.person.last_name %>
		<% else %>
			Anonymous
		<% end %>
	</a>
	<small>
	<%=rec.location %>
	(
		<%= rec.is_union ? rec.person.union.short_name : "" %>
		received via <%= rec.union.short_name %> 
	)
	<br/>
	</small>
</h3>
<p>
	<%=rec.volunteer ? "VOLUNTEER<br/>" : "" %>
	<%="#{h rec.industry}<br/>".html_safe unless rec.industry.blank? %>
	<%=rec.nature_of_employment%> 
	<%="by #{rec.company_name}" unless rec.company_name.blank? %>
	<%="@ #{rec.host_employer}" unless rec.host_employer.blank? %>
</p>
<table class="table table-condensed table-striped box-shadow">
	<thead>
		<tr>
			<td>
				<strong>
					<%=t('pay_and_conditions') %>
				</strong>
			</td>
			<td>
				<strong>
				<%=t('health_and_safety') %>
				</strong>
			</td>
			<td>
				<strong>
				<%=t('personal_impact') %>
				</strong>
			</td>
			<td>
				<strong>
				<%=t('financial_security') %>
				</strong>
			</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td <%=cell_style(rec.paid_fairly)%>>
				Paid Fair: <%=rec.paid_fairly %> 
			</td>
			<td <%=cell_style(rec.safe_work)%>>
				Safe work: <%=rec.safe_work %>
			</td>
			<td <%=cell_style(rec.predictable_hours)%>>
				Predictable Roster: <%=rec.predictable_hours %>
			</td>
			<td <%=cell_style(rec.financially_stable)%>>
				Bills ok: <%=rec.financially_stable %>
			</td>
		</tr>
		<tr>
			<td <%=cell_style(rec.compliant_employment)%>>
				Legal Employment: <%=rec.compliant_employment%>
			</td>
			<td <%=cell_style(rec.safe_work_explained)%>>
				Worksafe: <%= rec.safe_work_explained %>
			</td>
			<td <%=cell_style(rec.primary_carer)%>>
				Childcare: <%= rec.primary_carer %>
			</td>
			<td <%=cell_style(rec.accommodation_secure)%>>
				Accommodation ok: <%= rec.accommodation_secure %>
			</td>
		</tr>
		<tr>
			<td <%=cell_style(rec.could_speak_up)%>>
				Could speak up: <%=rec.could_speak_up%>
			</td>
			<td <%=cell_style(rec.discuss_safety)%>>
				Could speak up: <%= rec.discuss_safety %>
			</td>
			<td <%=cell_style(rec.entitlements)%>>
				Leave: <%= rec.entitlements %>
			</td>
			<td <%=cell_style(rec.feeling_secure)%>>
				Future secure: <%=rec.feeling_secure %>
			</td>
		</tr>
		<%if rec.union.short_name == "ANMF" %>
			<tr>
			<td <%=cell_style(rec.professional_development)%>>
				ProDev: <%=rec.professional_development%>
			</td>
			<td <%=cell_style(rec.induction)%>>
				Induction: <%= rec.induction %>
			</td>
			<td <%=cell_style(rec.entitlements)%>>
			</td>
			<td <%=cell_style(rec.feeling_secure)%>>
			</td>
		</tr>
		<% end %> 
	</tbody>
</table>
<% unless rec.solution.blank? %>
	<h4 class="no-left-margin">
		Solution
	</h4>
	<p>
		<%= rec.solution %>
	</p>
<% end %>

<% unless rec.summary.blank? %>
	<h4 class="no-left-margin">
		Story
	</h4>
	<blockquote>
		<%= profile_picture(rec.person) %>
		<%="HIDDEN: <S>".html_safe unless rec.enabled %>
			<span class="">
				<%= rec.summary %>
			</span>
		<%="</S>".html_safe unless rec.enabled %>
		<footer>
			<cite>
				<%= "profile url: #{rec.person.attachment.url}" if rec.person.attachment.url %>
				<%= "video url: #{rec.attachment.url}" if rec.attachment.url %>
			</cite> 
		</footer>
	</blockquote>
<% end %>
<h4 class="no-left-margin">Submission URL: <small><a href="<%=union_rec_url(rec.union, rec)%>"><%=union_rec_url(rec.union, rec)%></a></small></h4>

app/app/views/recs/_rec.html.erb
<blockquote>
	<%= profile_picture(rec.person) %>
	<%="HIDDEN: <S>".html_safe unless rec.enabled %>
		<span class="ellipsis">
			<%= rec.summary.split("\r\n").collect { |i| "#{h i}<br/>" }.join.html_safe
	 %>
		</span>
	<%="</S>".html_safe unless rec.enabled %>
	
	<%=link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, rec_path(rec) if current_person %>

	<video id="vid" class="<%=ios_video(rec.attachment)%> video" style="<%='display:none;' unless rec.attachment.url %>" controls >
		<source id="vid-source" src="<%=rec.attachment.url%>"/>
		Your browser doesn't support HTML 5 video
	</video>

	<footer>
		<cite>
			<%= "#{rec.display_name}" %>
			<%=link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_person_path(rec.person) if can_edit_union(rec.union) %>
		</cite> 
		<%="<small>submitted via #{rec.union.short_name}</small>".html_safe if current_person %>
		</footer>
</blockquote>

app/app/views/recs/_recs.html.erb
<% if current_person %>
	<strong>
		This page contains two sections to help submission
	</strong>

	<ol>
		<li>
				All submissions, hiding details of those who've requested anonymity - embed this in your union submission
		</li>
		<li>
			A directory of contact details for all submissions, including people requesting anonymity.  Include this as a separate document, that the inquiry won't publish.
		</li>
	</ol>
	
	<strong>OSX Instructions</strong>:  Copy and paste submissions into TextEdit, then copy and paste into pages or word.  This will keep images and tables.</br>

	<strong>Windows Instructions</strong>:  Copy and paste submissions into Word</br>

<h2 class="no-left-margin"> Submissions </h2>

<% end %> 

<% @recs.each do |rec| %>
  <hr/>
  <% if current_person %> 
  	<%= render partial: 'recs/detailed_rec', locals: {rec: rec} %>
  <% else %> 
  	<%= render rec %>
  <% end %>
<% end %>

<% if current_person %>
	<hr/>
	<h2 class="no-left-margin">Directory</h2>
	<table class="table table-condensed table-striped box-shadow">
		<thead>
			<tr>
				<td>
					<strong>
						Anonymous
					</strong>
				</td>
				<td>
					<strong>
						Name
					</strong>
				</td>
				<td>
					<strong>
						Email
					</strong>
				</td>
				<td>
					<strong>
						Mobile
					</strong>
				</td>
				<td>
					<strong>
						Gender
					</strong>
				</td>
				<td>
					<strong>
						Employment
					</strong>
				</td>
				<td>
					<strong>
						URL
					</strong>
				</td>
			</tr>
		</thead>
		<tbody>
			<% @recs.each do |rec| %>
			<tr>
				<td <%=cell_style(!rec.is_anonymous) %>>
					<%=rec.is_anonymous%>
				</td>
				<td>
					<%=rec.person.first_name%>
					<%=rec.person.last_name%>
					<%=", #{rec.location}" unless rec.location.blank? %>
				</td>
				<td>
					<%=rec.person.email%>
				</td>
				<td>
					<%=rec.person.mobile%>
				</td>
				<td>
					<%=rec.person.gender%>
				</td>
				<td>
					<%="#{rec.company_name}" unless rec.company_name.blank? %>
					<%="@ #{rec.host_employer}" unless rec.host_employer.blank? %>
				</td>
				<td>
					<small><%=union_rec_url(rec.union, rec)%></small>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table> 	
<% end %>

app/app/views/recs/_review.html.erb
<p id="notice"><%= notice %></p>
<hgroup>
  <h1 class="text-center">Thank you for your submission!</h1>
  <h3 class="text-center">Increase your impact by asking your friends and family to tell their story too</h3>
</hgroup>
<div style="text-align: center">
  <a style="display:inline-block" class="btn btn-primary" href="<%=facebook_share_rec_url(@rec.union, @rec.token, request)%>" target='_blank'><img src="<%=image_path('facebook.png')%>" alt="Facebook Logo" height="30px">Share on Facebook</a>

  <a style="display:inline-block" class="text-center btn btn-primary" href="<%=twitter_share_rec_url(@rec.union, @rec.token, request)%>"  target='_blank'><img src="<%=image_path('twitter.png')%>" alt="Twitter Logo" height="24px" style="margin: 3px;">Share on Twitter</a>

  <a style="display:inline-block" class="text-center btn btn-primary" href="mailto:?subject=<%=@rec.union.call_to_action%>&body=<%=CGI.escape(render partial: 'share_mail', formats: ['text'], locals: {union: @rec.union, referrer: @rec.token, rec: @rec, request: request}).gsub('+', ' ') %>"  target='_top'>
  	<img src="<%=image_path('envelope_white.png')%>" alt="Email Icon" height="24px" style="margin: 3px;">
  	Share by Email</a>
</div>

<%= render @rec %>
<%= render 'upload_video' %>

app/app/views/recs/_share_mail.html.erb
<h1><%= union.call_to_action %></h1>

<p>
<%= union.explanation %>
</p>
<p>
<%= union.submissions_heading %>
</p>
<p>
<%=link_to "#{request.protocol}#{request.host}/#{locale}/#{union.short_name}/new", "https://#{request.host}/#{locale}/#{union.short_name}/new"%>
</p>
<p>
Thanks<br/> 
<%= rec.person.first_name if rec %>

app/app/views/recs/_share_mail.text.erb
-- <%= union.call_to_action %> --

<%= union.explanation %>

<%= union.submissions_heading %>
<%="https://#{request.host}/#{locale}/#{union.short_name}/new"%>

Thanks 
<%= rec.person.first_name if rec %>

app/app/views/recs/_upload_video.html.erb
      <div class="hide_on_android">
        <div class="upload-feedback"></div>
        
        <%= form_for(@rec, url: video_upload_rec_path(@rec.token), :html => { multipart: true, id: 'fileupload',  class: "form", display: "none"}) do |f| %>
          <!-- requires javascript to switch on, for jquery file upload -->      
          <div class="bar-border" style="display:none; border-radius: 3px; border: 1px solid #aaa;width:100%; height:7px;">
            <div class="bar" style=" background-color: green; height: 6px; width:0%;"></div>
          </div>

          <div class="form-group file-button">
            <%= f.label :attachment, "Make you submission more compelling - Read it out on video" %><br>
            <%= f.file_field :attachment, accept: 'video/mov,video/mp4,video/ogg'  %>
          </div>

        <% end %>
      </div>


      <script type="text/javascript">
        var ready = function() {
          $("#fileupload").show();
          $("#fileupload").fileupload({
            datatype: 'json',
            add: function (e, data) {
              $(".file-button").hide();
              $('.bar-border').show();
              data.id = data.files[0].name;
              data.submit();
            }, 
            progress: function (e, data) {
              if (data.id) {
                progress = parseInt(data.loaded/data.total*90 /* withhold 10% for amazon s3 */, 10); 
                $('.bar').css('width', progress + '%');
              }
              console.log(progress);
            }, 
            done: function(e, data) {
              $("#vid-source").attr("src", data.result["url"]);
              $("#vid").show();
              $("#vid").load();
              $(".bar-border").hide();
              msg = "<p>We've got your video. Thanks!</p>"
              if (data.result["content_type"] == "video/mov" || data.result["content_type"] == "video/quicktime")
                msg += "<p> Unfortunately we can't publish it right away since its in apple format. But we'll get there eventually. </p>"

              $(".file-button").show();
              $(".upload-feedback").html(msg);
            }
          });
          $("#vid").load();
              
          if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) )
            $("#rec_attachment:file").filestyle({iconName: "glyphicon glyphicon-record", input:false, buttonText: "click here to record (EXPERIMENTAL)", badge: false});
            else
              $("#rec_attachment:file").filestyle({iconName: "glyphicon glyphicon-upload", input:false, buttonText: "drop and drag an mp4 or ogg file here", badge: false});

          if( /Android|webOS|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) )
            $(".hide_on_android").hide();

        };

        $(document).ready(ready);
        $(document).on('page:load', ready);
      </script>

app/app/views/recs/edit.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

		<h2>Editing Submission</h2>

		<%= render 'form' %>
	</div>
</div>

app/app/views/recs/embed_new.html.erb
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>

<div style="margin-bottom: 3em;">
	<h3 class='text-center'>We're going to prompt you with a series a questions the inquiry is looking to have answered</h3>

	<p class='text-center'>
		Your answers will be compiled into a story below that you should edit.
	</p>
</div>

<!-- TODO find where 100% height is coming from, causing switches to get tall -->
<!-- Bootstrap switches went nuts in embed because of the height: 100% rule -->
<style type="text/css">
	.bootstrap-switch .bootstrap-switch-handle-off, .bootstrap-switch .bootstrap-switch-handle-on, .bootstrap-switch .bootstrap-switch-label {
		height: inherit;
	}
</style>

<%= render 'form' %>

app/app/views/recs/embed_review.html.erb
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
  
<%= render 'review' %>

app/app/views/recs/index.html.erb
<%= render 'supergroups/share' %>
<%= render partial: 'supergroups/title' if @supergroup %>
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= link_to "Export Submissions", recs_path(format: "xls"), class: "btn btn-default pull-right" if current_person && owner? %>		
  	<%= render 'recs' %>
	</div>
</div>
<div id = "app-footer" class="clearfix text-center">
	<hr/>
	<small><%= ENV['AUTHORIZED_BY'] %></small>
</div>

app/app/views/recs/new.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

    <%= render partial: "shared/lang_picker", locals: { display_class: "pull-right" } %>

    <h1 class="text-center" style="color: <%= @union.background_colour %>">
      <!--<h1><%=t("new_story_title")%></h1>
      <h4><%=t("new_story_subtitle")%></h4>
    -->
      <%= @union.submissions_heading %><br/>
    </h1>

    <% if @union.union_rep.quote.url %>
      <div class="row">
        <blockquote>
          <p>
            <img src="<%=@union.union_rep.quote.url%>" />
            <%=@union.union_rep_quote%>
          </p>
          <footer>
            <cite><%=@union.union_rep_cite%></cite>
            <br/>
            <div class="text-right">
              <%=link_to t("new_story_read_all", count: Rec.count), all_union_path(id: @union.id) %>
            </div>
          </footer>
        </blockquote>

      </div>
    <% end %>
    
    

    <div style="margin-bottom: 3rem;" >
      <h3 class='text-center' style="color: <%= @union.background_colour %>"><%=t("new_story_explanation1")%></h3>

      <p class='text-center' >
        <%=t("new_story_explanation2")%></p>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/app/views/recs/review.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
		<%= render 'review' %>
	</div>
</div>